
package view;

import business.CustomerController;
import core.Helper;
import entity.Customer;
import javax.swing.DefaultComboBoxModel;


public class CustomerUI extends javax.swing.JFrame {
    private Customer customer;
    private CustomerController customerController;
    

    public CustomerUI(Customer customer) {
        this.customer = customer;
        this.customerController = new CustomerController();
        initComponents();
        setComboBox();
        this.setLocationRelativeTo(null);
        this.setTitle("Customer Add/Update");
        this.setVisible(true);
        setDefaultCloseOperation(CustomerUI.DISPOSE_ON_CLOSE);
        
        if(this.customer.getId()==0){
            this.lbl_title.setText("Add a Customer");
        }else{
            this.lbl_title.setText("Update a Customer");
            this.txt_customer_name.setText(this.customer.getName());
            this.txt_customer_email.setText(this.customer.getEmail());
            this.txt_customer_phone.setText(this.customer.getPhone());
            this.txt_customer_address.setText(this.customer.getAddress());
            this.cmb_customer_type.getModel().setSelectedItem(this.customer.getType());
            
        }
        
        
        
    }
    private void setComboBox(){
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for (Customer.TYPE type : Customer.TYPE.values()) {
              model.addElement(type.toString());
           }
          cmb_customer_type.setModel(model);

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_title = new javax.swing.JLabel();
        lbl_customer_name = new javax.swing.JLabel();
        txt_customer_name = new javax.swing.JTextField();
        lbl_customer_type = new javax.swing.JLabel();
        cmb_customer_type = new javax.swing.JComboBox<>();
        lbl_customer_phone = new javax.swing.JLabel();
        txt_customer_phone = new javax.swing.JTextField();
        lbl_customer_email = new javax.swing.JLabel();
        txt_customer_email = new javax.swing.JTextField();
        lbl_customer_address = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_customer_address = new javax.swing.JTextArea();
        btn_save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_title.setText("jLabel1");

        lbl_customer_name.setText("Customer Name:");

        lbl_customer_type.setText("Customer Type:");

        cmb_customer_type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmb_customer_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_customer_typeActionPerformed(evt);
            }
        });

        lbl_customer_phone.setText("Phone:");

        lbl_customer_email.setText("Email:");

        lbl_customer_address.setText("Customer Address:");

        txt_customer_address.setColumns(20);
        txt_customer_address.setRows(5);
        jScrollPane1.setViewportView(txt_customer_address);

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_customer_phone)
                    .addComponent(lbl_customer_type, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_customer_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_customer_name)
                    .addComponent(cmb_customer_type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_customer_phone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_customer_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_customer_email)
                    .addComponent(lbl_customer_address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(btn_save)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_customer_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_customer_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_customer_type)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_customer_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_customer_phone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_customer_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_customer_email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_customer_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_customer_address)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btn_save)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_customer_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_customer_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_customer_typeActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        if(this.txt_customer_name.getText().isEmpty() || this.txt_customer_phone.getText().isEmpty()){
            Helper.showMsg("fill");
        }else if(!this.txt_customer_email.getText().isEmpty() && !Helper.isEmailValid(this.txt_customer_email.getText())){
            Helper.showMsg("Please, enter a valid email.");
            
        }else{
            boolean result = false;
            this.customer.setName(this.txt_customer_name.getText());
            this.customer.setPhone(this.txt_customer_phone.getText());
            this.customer.setEmail(this.txt_customer_email.getText());
            this.customer.setAddress(this.txt_customer_address.getText());
            this.customer.setType(Customer.TYPE.valueOf(this.cmb_customer_type.getSelectedItem().toString()));

            if (this.customer.getId()==0){
                result = this.customerController.save(this.customer);
            }else{
                result = this.customerController.update(this.customer);
            }
            
            
            
            if(result){
                Helper.showMsg("done");
                this.dispose();
            }else{
                Helper.showMsg("error");
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmb_customer_type;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_customer_address;
    private javax.swing.JLabel lbl_customer_email;
    private javax.swing.JLabel lbl_customer_name;
    private javax.swing.JLabel lbl_customer_phone;
    private javax.swing.JLabel lbl_customer_type;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextArea txt_customer_address;
    private javax.swing.JTextField txt_customer_email;
    private javax.swing.JTextField txt_customer_name;
    private javax.swing.JTextField txt_customer_phone;
    // End of variables declaration//GEN-END:variables
}
